Repository newrelic/opensource-website, pull requests merged in 2020-07, with the labels that each got.

#516 fix: add responsive styling to images #505
  src/components/styles.scss
Labels: bug

#551 chore: install gatsby-theme-newrelic and replace the buttons
  gatsby-config.js
  gatsby/create-pages.js
  jest-preprocess.js
  jest.config.js
  package-lock.json
  package.json
  setup-test-env.js
  src/components/CookieApprovalDialog.js
  src/components/CookieApprovalDialog.module.scss
  src/components/GlobalHeader.js
  src/components/GlobalHeader.module.scss
  src/components/ProjectSearchInput.module.scss
  src/components/__tests__/__snapshots__/Header.spec.js.snap
  src/components/styles.scss
  src/pages/__tests__/__snapshots__/collection.spec.js.snap
  src/pages/__tests__/__snapshots__/external-projects.spec.js.snap
  src/pages/__tests__/__snapshots__/index.spec.js.snap
  src/pages/__tests__/__snapshots__/oss-category.spec.js.snap
  src/pages/explore-projects.js
  src/pages/external-projects.js
  src/pages/external-projects.module.scss
  src/pages/oss-category.js
  src/templates/__tests__/__snapshots__/external-project-page.spec.js.snap
  src/templates/external-project-page.js
  src/templates/project-page.js
  src/templates/project-page.module.scss
Labels: enhancement

#564 fixed broken link to devsite
  src/pages/nerdpacks.js
Labels: documentation

#572 feat: add collections to homepage + collections landing page
  src/components/HomePageHighlights.js
  src/components/HomePageHighlights.module.scss
  src/components/HomePageInternalProjects.module.scss
  src/components/HomepageCollection.js
  src/components/HomepageCollection.module.scss
  src/components/PageHeading.js
  src/components/ProjectModule.module.scss
  src/components/SimpleProjectModule.module.scss
  src/data/navigation.json
  src/images/home-collection-mask-dark.png
  src/images/home-collection-mask.png
  src/pages/collection.module.scss
  src/pages/collections.js
  src/pages/home-page.module.scss
  src/pages/index.js
Labels: enhancement
