Repository newrelic/opensource-website, pull requests merged in 2021-03, with the labels that each got.

#690 Add nr1-cambio
  src/data/project-main-content/globalsoftWigilabs-nr1-cambio.mdx
  src/data/projects/globalsoftWigilabs-nr1-cambio.json
Labels: waiting on contributor

#700 chore: added docs site and dev site fixes
  src/data/project-main-content/newrelic-developer-website.mdx
  src/data/project-main-content/newrelic-docs-website.mdx
  src/data/projects/newrelic-developer-website.json
  src/data/projects/newrelic-docs-website.json
Labels: content

#702 [Snyk] Upgrade gatsby-plugin-mdx from 1.2.52 to 1.10.0
  package-lock.json
  package.json
Labels: sp:2

#701 [Snyk] Upgrade: gatsby, gatsby-image, gatsby-plugin-manifest, gatsby-plugin-offline, gatsby-plugin-sass, gatsby-plugin-sharp, gatsby-remark-copy-linked-files, gatsby-remark-images, gatsby-source-filesystem, gatsby-transformer-json
  package-lock.json
  package.json
Labels: help wanted, sp:2

#708 [Snyk] Upgrade @mdx-js/mdx from 1.6.19 to 1.6.22
  package-lock.json
  package.json
Labels: help wanted, snyk

#729 chore: add nrql status widget project (custom viz)
  src/data/projects/newrelic-experimental-nr1-nrql-status-widget.json
Labels: content

#725 Yarn switch
  .github/workflows/pr.yml
  .github/workflows/project-stats.yml
  .github/workflows/release.yml
  README.md
  amplify.yml
  docs/Emergency-Runbook.md
  package-lock.json
  package.json
  src/components/ProjectSearch.js
  src/data/project-main-content/newrelic-opensource-website.mdx
  yarn.lock
Labels: enhancement

#733 chore: missing yarn configurations
  .github/workflows/pr.yml
  .github/workflows/project-stats.yml
  .github/workflows/release.yml
  .releaserc
Labels: P3, bug
