Repository newrelic/opensource-website, pull requests merged in 2021-04, with the labels that each got.

#743 feat: adds tessen config and library
  gatsby-config.js
  package.json
  static/tessen.min-1.3.0.js
  yarn.lock
Labels: analytics

#745 chore: add project json and mdx files for AVPlayer and ExoPlayer Vide…
  src/data/project-main-content/newrelic-video-avplayer-ios-tvos.mdx
  src/data/project-main-content/newrelic-video-exoplayer-android.mdx
  src/data/projects/newrelic-video-avplayer-ios-tvos.json
  src/data/projects/newrelic-video-exoplayer-android.json
Labels: sp:1

#764 chore: added browser agent
  src/data/project-main-content/newrelic-newrelic-browser-agent.mdx
  src/data/projects/newrelic-newrelic-browser-agent.json
Labels: gatsbysites, sp:1
